<a href="https://colab.research.google.com/github/vallurusandeepkumar63-coder/week-1-ana-1/blob/main/WEEK_1_ANA_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Introduction**

The dataset (APMS – Annual Status of Education Report type data) contains structured information collected from surveys. It includes multiple fields such as demographic details, education-related indicators, and categorical/numerical variables.


•	The data is stored in CSV (Comma-Separated Values) format

•	Each row represents a record/observation

•	Each column represents a feature/attribute

•	The dataset may include:

o	Numeric data (e.g., age, scores)

o	Categorical data (e.g., gender, category)

o	Missing values (empty or null fields)

The dataset is useful for:

•	Data analysis

•	Educational insights

•	Statistical modelling

**Technology Used**

1. Python

Python is used as the main programming language because it is:

•	Easy to use

•	Powerful for data analysis

•	Supports many libraries


2. Colab  Notebook

Colab Notebook is used for:

•	Writing and executing code step-by-step

•	Combining code, output, and explanations

•	Visualization and interactive analysis

3. Pandas

Pandas is the main library used for handling data.

Key uses:

•	Reading CSV files → pd.read_csv()

•	Data cleaning

•	Data manipulation

•	Statistical analysis


**Dataset Profiling (APMS)**

Dataset profiling helps to understand the structure and quality of data.

In [9]:
import pandas as pd

In [10]:
df = pd.read_csv("/content/anxiety_depression_data.csv")

In [11]:
df.head()

,Age,Gender,Education_Level,Employment_Status,Sleep_Hours,Physical_Activity_Hrs,Social_Support_Score,Anxiety_Score,Depression_Score,Stress_Level,...,Chronic_Illnesses,Medication_Use,Therapy,Meditation,Substance_Use,Financial_Stress,Work_Stress,Self_Esteem_Score,Life_Satisfaction_Score,Loneliness_Score
0,56,Male,Bachelor's,Unemployed,6.0,0.4,3,4,2,9,...,0,NaN,0,1,NaN,4,3,7,5,1
1,69,Female,Bachelor's,Retired,8.8,2.8,6,18,7,6,...,0,NaN,1,0,NaN,1,4,7,4,6
2,46,Female,Master's,Employed,5.3,1.6,5,5,13,8,...,0,NaN,0,1,NaN,8,7,8,1,1
3,32,Female,High School,Unemployed,8.8,0.5,4,6,3,4,...,1,NaN,0,0,NaN,7,4,8,4,4
4,60,Female,Bachelor's,Retired,7.2,0.7,2,7,15,3,...,0,NaN,1,1,Frequent,8,9,5,7,7

In [12]:
df.tail()

,Age,Gender,Education_Level,Employment_Status,Sleep_Hours,Physical_Activity_Hrs,Social_Support_Score,Anxiety_Score,Depression_Score,Stress_Level,...,Chronic_Illnesses,Medication_Use,Therapy,Meditation,Substance_Use,Financial_Stress,Work_Stress,Self_Esteem_Score,Life_Satisfaction_Score,Loneliness_Score
1195,23,Female,Other,Student,5.1,0.1,7,16,15,5,...,0,Occasional,0,0,NaN,2,8,7,6,5
1196,43,Female,Master's,Employed,8.9,0.4,9,19,4,9,...,0,NaN,0,1,NaN,8,9,7,6,4
1197,71,Female,PhD,Retired,6.0,0.1,2,15,4,2,...,0,NaN,0,1,NaN,2,9,9,3,7
1198,21,Male,Other,Employed,8.5,2.7,8,12,20,2,...,1,NaN,0,0,NaN,8,5,1,3,7
1199,36,Male,Other,Employed,4.4,2.6,7,10,10,5,...,0,NaN,1,0,Frequent,7,2,6,4,8

**1.	Row Count**

In [13]:
print("Row count:", len(df))

Row count: 1200

**2. Column Count**

In [14]:
print("Column count:", len(df.columns))

Column count: 21

**3. Field Types**

In [15]:
print(df.dtypes)

Age                                int64
Gender                            object
Education_Level                   object
Employment_Status                 object
Sleep_Hours                      float64
Physical_Activity_Hrs            float64
Social_Support_Score               int64
Anxiety_Score                      int64
Depression_Score                   int64
Stress_Level                       int64
Family_History_Mental_Illness      int64
Chronic_Illnesses                  int64
Medication_Use                    object
Therapy                            int64
Meditation                         int64
Substance_Use                     object
Financial_Stress                   int64
Work_Stress                        int64
Self_Esteem_Score                  int64
Life_Satisfaction_Score            int64
Loneliness_Score                   int64
dtype: object

**4. Missing Values**

In [16]:
missing = df.isnull().sum()
missing_rate = (missing / len(df)) * 100

print(pd.DataFrame({
    "Missing Count": missing,
    "Missing %": missing_rate
}))

                               Missing Count  Missing %
Age                                        0       0.00
Gender                                     0       0.00
Education_Level                            0       0.00
Employment_Status                          0       0.00
Sleep_Hours                                0       0.00
Physical_Activity_Hrs                      0       0.00
Social_Support_Score                       0       0.00
Anxiety_Score                              0       0.00
Depression_Score                           0       0.00
Stress_Level                               0       0.00
Family_History_Mental_Illness              0       0.00
Chronic_Illnesses                          0       0.00
Medication_Use                           747      62.25
Therapy                                    0       0.00
Meditation                                 0       0.00
Substance_Use                            834      69.50
Financial_Stress                           0       0.00
Work_Stress                                0       0.00
Self_Esteem_Score                          0       0.00
Life_Satisfaction_Score                    0       0.00
Loneliness_Score                           0       0.00

**5. Outlier Detection**

In [17]:
import numpy as np

numeric_cols = df.select_dtypes(include=np.number)

Q1 = numeric_cols.quantile(0.25)
Q3 = numeric_cols.quantile(0.75)
IQR = Q3 - Q1

outliers = ((numeric_cols < (Q1 - 1.5 * IQR)) |
            (numeric_cols > (Q3 + 1.5 * IQR)))

print(outliers.sum())

Age                                0
Sleep_Hours                        6
Physical_Activity_Hrs             75
Social_Support_Score               0
Anxiety_Score                      0
Depression_Score                   0
Stress_Level                       0
Family_History_Mental_Illness      0
Chronic_Illnesses                  0
Therapy                          252
Meditation                         0
Financial_Stress                   0
Work_Stress                        0
Self_Esteem_Score                  0
Life_Satisfaction_Score            0
Loneliness_Score                   0
dtype: int64

**6. Descriptive Stats**

In [18]:
df.describe()
print(df)

      Age  Gender Education_Level Employment_Status  Sleep_Hours  \
0      56    Male      Bachelor's        Unemployed          6.0
1      69  Female      Bachelor's           Retired          8.8
2      46  Female        Master's          Employed          5.3
3      32  Female     High School        Unemployed          8.8
4      60  Female      Bachelor's           Retired          7.2
...   ...     ...             ...               ...          ...
1195   23  Female           Other           Student          5.1
1196   43  Female        Master's          Employed          8.9
1197   71  Female             PhD           Retired          6.0
1198   21    Male           Other          Employed          8.5
1199   36    Male           Other          Employed          4.4

      Physical_Activity_Hrs  Social_Support_Score  Anxiety_Score  \
0                       0.4                     3              4
1                       2.8                     6             18
2                       1.6                     5              5
3                       0.5                     4              6
4                       0.7                     2              7
...                     ...                   ...            ...
1195                    0.1                     7             16
1196                    0.4                     9             19
1197                    0.1                     2             15
1198                    2.7                     8             12
1199                    2.6                     7             10

      Depression_Score  Stress_Level  ...  Chronic_Illnesses  Medication_Use  \
0                    2             9  ...                  0             NaN
1                    7             6  ...                  0             NaN
2                   13             8  ...                  0             NaN
3                    3             4  ...                  1             NaN
4                   15             3  ...                  0             NaN
...                ...           ...  ...                ...             ...
1195                15             5  ...                  0      Occasional
1196                 4             9  ...                  0             NaN
1197                 4             2  ...                  0             NaN
1198                20             2  ...                  1             NaN
1199                10             5  ...                  0             NaN

     Therapy  Meditation  Substance_Use Financial_Stress  Work_Stress  \
0          0           1            NaN                4            3
1          1           0            NaN                1            4
2          0           1            NaN                8            7
3          0           0            NaN                7            4
4          1           1       Frequent                8            9
...      ...         ...            ...              ...          ...
1195       0           0            NaN                2            8
1196       0           1            NaN                8            9
1197       0           1            NaN                2            9
1198       0           0            NaN                8            5
1199       1           0       Frequent                7            2

      Self_Esteem_Score  Life_Satisfaction_Score  Loneliness_Score
0                     7                        5                 1
1                     7                        4                 6
2                     8                        1                 1
3                     8                        4                 4
4                     5                        7                 7
...                 ...                      ...               ...
1195                  7                        6                 5
1196                  7                        6                 4
1197                  9                        3                 7
1198                  1                        3                 7
1199                  6                        4                 8

[1200 rows x 21 columns]